### ISSUE TITLE
Build ERROR - Undefined Driver_I2C0

### ISSUE THREAD

**Issue by purdurnr** [RobertRostohar/NXP_Sensor_SDK#3]
I have been able to run "layer list" and "convert" commands for the example projects.  
I am focused on the frdmk22f_a8974 builds.  I have that board plugged in.
I get following error when I build any of the cprj files.
Any suggestions on what step I am missing?

I look up and Driver_I2C0 is defined in frdm_k22f.h as "extern ARM_DRIVER_I2C Driver_I2C0;"
I run the following:   cbuild fxls8974cf_interrupt.debug+frdmk22f_a8974.cprj

Succesfully links.  Then fails with following:
FAILED: C:/GIT/NXP_Sensor_SDK/examples/issdk/sensors/fxls8974cf/interrupt/out/fxls8974cf_interrupt/frdmk22f_a8974/debug/fxls8974cf_interrupt.debug+frdmk22f_a8974.axf
cmd.exe /C "cd . && C:\Keil_v5\ARM\ARMCLANG\bin\armlink.exe --cpu=Cortex-M4 --scatter="C:/GIT/NXP_Sensor_SDK/boards/frdmk22f/RTE/Device/MK22FN512VLH12/MK22FN512xxx12_flash.scf"  --entry=Reset_Handler --strict --info summarysizes --remove --keep=*(.crp) --keep=*(.FlashConfig) --diag_suppress 6314,6319    --via=CMakeFiles\fxls8974cf_interrupt.debug+frdmk22f_a8974.rsp -o C:\GIT\NXP_Sensor_SDK\examples\issdk\sensors\fxls8974cf\interrupt\out\fxls8974cf_interrupt\frdmk22f_a8974\debug\fxls8974cf_interrupt.debug+frdmk22f_a8974.axf  --list=C:\GIT\NXP_Sensor_SDK\examples\issdk\sensors\fxls8974cf\interrupt\out\fxls8974cf_interrupt\frdmk22f_a8974\debug\fxls8974cf_interrupt.debug+frdmk22f_a8974.axf.map && cmd.exe /C "cd /D C:\GIT\NXP_Sensor_SDK\examples\issdk\sensors\fxls8974cf\interrupt\tmp\fxls8974cf_interrupt\frdmk22f_a8974\debug && c:\Keil_v5\ARM\ARMCLANG\bin\fromelf.exe --i32combined --output C:/GIT/NXP_Sensor_SDK/examples/issdk/sensors/fxls8974cf/interrupt/out/fxls8974cf_interrupt/frdmk22f_a8974/debug/fxls8974cf_interrupt.debug+frdmk22f_a8974.hex C:/GIT/NXP_Sensor_SDK/examples/issdk/sensors/fxls8974cf/interrupt/out/fxls8974cf_interrupt/frdmk22f_a8974/debug/fxls8974cf_interrupt.debug+frdmk22f_a8974.axf && cd /D C:\GIT\NXP_Sensor_SDK\examples\issdk\sensors\fxls8974cf\interrupt\tmp\fxls8974cf_interrupt\frdmk22f_a8974\debug && c:\Keil_v5\ARM\ARMCLANG\bin\fromelf.exe --bin --output C:/GIT/NXP_Sensor_SDK/examples/issdk/sensors/fxls8974cf/interrupt/out/fxls8974cf_interrupt/frdmk22f_a8974/debug/fxls8974cf_interrupt.debug+frdmk22f_a8974.bin C:/GIT/NXP_Sensor_SDK/examples/issdk/sensors/fxls8974cf/interrupt/out/fxls8974cf_interrupt/frdmk22f_a8974/debug/fxls8974cf_interrupt.debug+frdmk22f_a8974.axf""
Warning: L9931W: Your license for feature mdk_pro_compiler5 will expire in 29 days
Error: L6218E: Undefined symbol Driver_I2C0 (referred from fxls8974cf_interrupt.o).

**Comment by purdurnr** [comment]
Using compiler pointed at Keil_v5. 
Inside About uVision it indicates C Compiler: v6.18
So that matches the request in overview.

-- The ASM compiler identification is ARMClang
-- Found assembler: c:/Keil_v5/ARM/ARMCLANG/bin/armclang.exe

**Comment by purdurnr** [comment]
I tried to open the .cprj output in my Keil uVision5 tools.  It loads, but has 12 errors with missing files.
All files are shown in Project Explorer and Manage project items.  However, seems environment is not set correctly when imported.
I will wait until you have time to review after holiday.
Thanks for support.

**Comment by RobertRostohar** [comment]
It should build out of the box.

> Succesfully links. Then fails with following:

Not sure what fails when link is successful. It looks as linking fails.

The missing `Driver_I2C0` could indicate the wrong` RTE_Device.h` being used. That could be the case with older CMSIS-Toolbox. Are you using the latest version 1.4.0? Are you modifying the source code?

Please check the following:
- clean checkout of the repo ('main' or 'develop' branch)
- using CMSIS-Toolbox 1.4.0
- using Arm Compiler 6.18 or later (I'm using 6.19)
- using CMake 3.18.0 or higher (I'm using 3.24.1)
- using Ninja 1.10.0 or higher (I'm using 1.11.0)
- using all CMSIS-Packs specified in the .csolution.yml

Run:
```
cd examples\issdk\sensors\fxls8974cf\interrupt
csolution convert fxls8974cf_interrupt.csolution.yml
cbuild fxls8974cf_interrupt.debug+frdmk22f_a8974.cprj
```

There should not be any errors during `csolution convert` or `cbuild`.

If it still fails, we could check the generated .cprj and also .cbuild.yml files.

The .cprj can be also imported in Keil uVision. I believe that the latest uVision from MDK 5,38 is required to build the project successfully. I'm using MDK 5.38 and the imported project builds without errors.

**Comment by purdurnr** [comment]
Error was caused by environment variables being reset to older values within my Git-Bash terminal.
Once I updated to correct settings... worked out of the box.

**Comment by purdurnr** [comment]
A note to self to recall FIX:  Also need to fix RTE_device.h where RTE_I2C4 was not defined.
