### ISSUE TITLE
Add Ninja to software prerequisite 

### ISSUE THREAD

**Issue by APurohit10** [RobertRostohar/NXP_Sensor_SDK#5]
cbuild has a dependency on Ninja package. The README.md should highlight this software prerequisite to install Ninja and set up into environment.

**Comment by RobertRostohar** [comment]
README.md lists [CMSIS-Toolbox 1.4.0](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/releases/tag/1.4.0) as prerequisite.

There is a link to [Setup and installation](https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/installation.md) which describes how to install and setup cbuild including Ninja.

We don't want to repeat this information in README.md of projects using cbuild.

**Comment by APurohit10** [comment]
@RobertRostohar, that's fair enough. Thanks for sharing this detail (i certainly missed it and struggled).
